# This is the Data Quality project configuration for consenting practice requirements
name: 'Oncology'
version: '1.0.0'

config-version: 2
vars:
  Oncology_src_catalog: 'catalog_name'
  Oncology_src_schema: 'schema_name'


profile: 'Oncology'

model-paths: ["../../models"]
analysis-paths: ["../../analyses"]
test-paths: ["../../tests"]
seed-paths: ["../../seeds"]
macro-paths: ["../../macros"]
snapshot-paths: ["../../snapshots"]
packages-install-path: "../../dbt_packages"

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  elementary:
    +schema: "elementary"
    # Include the following line if you only want Elementary to run when in a specified environment
    enabled: "{{ target.name in ['cp'] }}"
  
