oncology:
  target: cp
  outputs:
    cp:
      catalog: catalo_anme
      host: hostname
      http_path:http_path_specify
      dbt_log_path: /logs
      schema: schema_name
      threads: 8
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
      type: databricks
